environment: development
namespace: order-api
host: "*"

apphost: k8s

orderapi:
  label:
    name: orderapi
    version: stage

  container:
    name: orderapi
    pullPolicy: Always
    image: demokubernetesworkshopacr.azurecr.io/petshoporders
    tag: latest
    port: 80
  replicas: 1

  service:
    port: 8887
    type: ClusterIP
