environment: development
namespace: product-api
host: "*"

apphost: k8s

productapi:
  label:
    name: productapi
    version: stage

  container:
    name: productapi
    pullPolicy: Always
    image: demokubernetesworkshopacr.azurecr.io/petshopproducts
    tag: latest
    port: 80
  replicas: 1

  service:
    port: 8887
    type: ClusterIP
