apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-orderapi-service
  labels:
    app: {{ .Values.orderapi.label.name }}
spec:
  ports:
  - name: tcp
    port: {{ .Values.orderapi.service.port }}
    protocol: TCP
    targetPort: {{ .Values.orderapi.container.port }}
  selector:
    app: {{ .Values.orderapi.label.name }}
  type: {{ .Values.orderapi.service.type }}
