environment: development

apphost: k8s

products:
  label:
    name: products

  container:
    name: products
    pullPolicy: Always
    image: demokubernetesworkshopacr.azurecr.io/petshoporders
    tag: latest
    port: 80
  replicas: 3

  service:
    port: 8888
    type: NodePort

orders:
  label:
    name: orders

  container:
    name: orders
    pullPolicy: Always
    image: demokubernetesworkshopacr.azurecr.io/petshoporders
    tag: latest
    port: 80
  replicas: 3

  service:
    port: 8889
    type: NodePort
