apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-productapi-service
  labels:
    app: {{ .Values.productapi.label.name }}
spec:
  ports:
  - name: tcp
    port: {{ .Values.productapi.service.port }}
    protocol: TCP
    targetPort: {{ .Values.productapi.container.port }}
  selector:
    app: {{ .Values.productapi.label.name }}
  type: {{ .Values.productapi.service.type }}
