apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-productapi-virtualservice
  namespace: {{.Values.namespace}}
spec:
  hosts:
    - {{.Values.host}} # copy the value in the gateway hosts
  gateways:
    - istio-my-service-gateway/istio-my-gateway    # gateway name preceded by namespace
  http: 
  - match: 
    # - headers: 
    #     canary: # any value like key value pair. - "canary" is a key. 
    #       exact: "true" # when its "true" it will pick the below destination. 
    # route: 
    # - destination: 
    #     host: {{ .Release.Name }}-productapi-service.{{.Values.namespace}}.svc.cluster.local    #service-name.namespace.svc.cluster.local 
    #     subset: canary-subset
 

  - route: 
    - destination: 
        host: {{ .Release.Name }}-productapi-service.{{.Values.namespace}}.svc.cluster.local    #service-name.namespace.svc.cluster.local 
        subset: production-subset
