apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-products-service
  labels:
    app: {{ .Values.products.label.name }}
spec:
  ports:
  - port: {{ .Values.products.service.port }}
    protocol: TCP
    targetPort: {{ .Values.products.container.port }}
  selector:
    app: {{ .Values.products.label.name }}
  type: {{ .Values.products.service.type }}
